<?php

/**
 * @file
 * It contains all the hooks needed for the functionalities of the module.
 */

use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_token_info.
 *
 * @return array
 *   An associative array of available tokens and token types. The outer array has two components: types and tokens.
 */
function dcc_gtd_scheduler_token_info() {
  $activeTrainingTitleTokenGenerator = Drupal::service('dcc_schedule.active_training_title_token_generator');
  return $activeTrainingTitleTokenGenerator->getTokenInfo();
}

/**
 * Implements hook_tokens.
 *
 * @return array
 *   An associative array of replacement values, keyed by the raw [type:token] strings from the original text.
 */
function dcc_gtd_scheduler_tokens($type, array $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {

  $activeTrainingTitleTokenGenerator = Drupal::service('dcc_schedule.active_training_title_token_generator');
  $replacements = $activeTrainingTitleTokenGenerator->generateToken($type, $tokens);

  return $replacements;

}
