<?php

use Drupal\Core\Render\BubbleableMetadata;

/**
 * Hook that creates a token in token list.
 *
 * @return array
 */
function dcc_gtd_scheduler_token_info() {
  $types['scheduler'] = array(
    'name' => 'Active Scheduler',
    'description' => 'Tokens related to the currentlly active Training.',
  );

  $tokens_array = [
    'scheduler' => [
      'title' => [
        'name' => 'title',
        'description' => 'The title of the currentlly active training',
      ],
    ],
  ];

  return array(
    'types' => $types,
    'tokens' => $tokens_array,
  );
}

function dcc_gtd_scheduler_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {

  $replacements = array();

  if($type = 'scheduler')
  {
    $container = Drupal::getContainer();
    $scheduleManager = $container->get('dcc_schedule.manager');
    $node = $scheduleManager->getActiveScheduler();

      foreach ($tokens as $name => $original) {
        if($original == "[scheduler:title]")
              $replacements[$original] = $node->getTitle();
      }

  }

  return $replacements;
}
