<?php

/**
 * @file
 * Contains hook implementations.
 */

use Drupal\dcc_gtd_registration\Form\GlobalTrainingRegistrationForm;

/**
 * Implements hook_mail().
 *
 * {@inheritdoc}
 */
function dcc_email_mail($key, &$message, $params) {
  switch ($key) {
    case GlobalTrainingRegistrationForm::GLOBAL_TRAINING_REGISTRATION_EMAIL_KEY:
      /* @var \Drupal\dcc_email\EmailFormatter $formatter */
      $formatter = \Drupal::service('dcc_email.email_formatter');

      $message = $formatter->format($key, $message, $params);
      break;
  }
}

/**
 * Implements hook_theme().
 *
 * {@inheritdoc}
 */
function dcc_email_theme($existing, $type, $theme, $path) {
  return [
    GlobalTrainingRegistrationForm::GLOBAL_TRAINING_REGISTRATION_EMAIL_KEY => [
      'variables' => [
        'first_name' => NULL,
        'last_name' => NULL,
        'activation_link' => NULL,
        'cancel_link' => NULL,
      ],
      'template' => 'global-registration-email',
    ],
  ];
}
