<?php

/**
 * @file
 * Contains hook implementations.
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function dcc_seo_form_eu_cookie_compliance_config_form_alter(&$form) {
  unset($form['eu_cookie_compliance']['popup_disagree_button_message']);
  unset($form['eu_cookie_compliance']['popup_link']);
  unset($form['eu_cookie_compliance']['popup_link_new_window']);
}

/**
 * Implements hook_page_attachments().
 */
function dcc_seo_page_attachments_alter(&$attachments) {
  unset($attachments['#attached']['drupalSettings']['eu_cookie_compliance']['popup_link']);
  unset($attachments['#attached']['drupalSettings']['eu_cookie_compliance']['popup_link_new_window']);
}
