<?php

/**
 * @file
 * Contains hook implementations.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;

define('ACTIVATION_STATUS_PAGE', 'dcc_gtd_registration_activation_status_page');

/**
 * Implements hook_theme().
 *
 * {@inheritdoc}
 */
function dcc_gtd_registration_theme($existing, $type, $theme, $path) {
  return [
    ACTIVATION_STATUS_PAGE => [
      'variables' => [
        'first_name' => NULL,
        'last_name' => NULL,
        'message' => NULL,
      ],
      'template' => 'registration-activation-page',
    ],
  ];
}

/**
 * Implements hook_js_alter().
 *
 * {@inheritdoc}
 */
function dcc_gtd_registration_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  $key = 'https://www.google.com/recaptcha/api.js';

  if (array_key_exists($key, $javascript)) {
    // Loads a language specific version of the recaptcha.
    $langCode = \Drupal::service('language_manager')->getCurrentLanguage()->getId();
    $javascript[$key]['data'] .= '?hl=' . $langCode;
  }
}
